export const LOADING_SCREEN = "LOADINGSCREEN";
export const ERROR_SCREEN = "ERRORSCREEN";
export const LOADED_SCREEN = "LOADEDSCREEN";
export const EDIT_USERNAME = "EDITUSERNAME";
export const EDIT_PASSWORD = "EDITPASSWORD";
export const EDIT_FIRST_NAME = "EDITFIRSTNAME";
export const EDIT_LAST_NAME = "EDITLASTNAME";
