export const TRAFFIC_LOADED_SUCCESS = "TRAFFIC LOADED SUCCESS";
export const TRAFFIC_LOADED_FAILED = "TRAFFIC_LOADED_FAIED";
export const START_TRAFFIC_BUFFERRING = "START TRAFFIC BUFFERRING";
export const END_TRAFFIC_BUFFERRING = "END TRAFFIC BUFFERRING";
